services:
  backend:
    image: ghcr.io/ksaweryzietara/cargoflow:latest
    container_name: backend
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/cargoflow
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - ADMIN_LOGIN=admin
      - ADMIN_PASSWORD=admin
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=cargoflow
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
  web:
    image: ghcr.io/ksaweryzietara/cargoflow-web:latest
    container_name: web
    ports:
      - 3000:3000
